### ISSUE TITLE
Conversion of {} and []

### ISSUE THREAD

**Issue by danlong005** [danlong005/RPGAPI#5]
These aren't converting correctly.

**Comment by mlstoppa** [comment]
I had the same problem even after having downloaded the last version.
After a few tries, I solved it this way: 
firstly, the job keeps the system's CCSID w/o any change
secondly, I made a change in RPGAPI, just before returning the response: instead of translating response's data using new QJSON table, I moved data into a new variable data_utf8 which was declared same length as data but ccsid(1208) which corresponds to utf-8; then data_utf8 is returned through the socket.
This solution works for me, so I can keep the job CCSID and have response data automatically and correctly translated by the system w/o using tables or iconv().
I can't think of any drawbacks in this solution, but it doesn't mean there aren't any. 
Do you think a structured solution can be built upon it?

**Comment by danlong005** [comment]
Yes. The machine im working on doesnt allow 1208. Im moving to another machine so i can do what u have described.  Your solution is the best.
